# Project
project:
    pattern: /project(/id)
    controller: Project
    extra:
        layout: project
        menu:
            mainmenu: projects

# Projects
projects:
    pattern: /projects(/page)
    controller: Projects
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: projects
        menu:
            mainmenu: projects
