# Project
project:
    pattern: /project/(id)
    controller: Project
    extra:
        layout: project
        active:
            mainmenu: projects

# Projects
projects:
    pattern: /projects(/page)
    controller: Projects
    extra:
        layout: projects
        active:
            mainmenu: projects
